###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: a23dd986
# Executable: /home/neeraj/BTP/ChampSim/bin/champsim
######

###
# Build ID: a23dd986
# Source: /home/neeraj/BTP/ChampSim/src
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj
###

a23dd986_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj
a23dd986_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/src/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj/%.o, $(wildcard /home/neeraj/BTP/ChampSim/src/*.cc))
$(a23dd986_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/src
$(a23dd986_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj/%.o: /home/neeraj/BTP/ChampSim/src/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/obj/*.d)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_objs_0) | /home/neeraj/BTP/ChampSim/bin
$(a23dd986_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
build_dirs += $(a23dd986_dirs_0) /home/neeraj/BTP/ChampSim/bin
build_objs += $(a23dd986_objs_0)
executable_name += /home/neeraj/BTP/ChampSim/bin/champsim

###
# Build ID: a23dd986_btbDbasic_btb
# Source: /home/neeraj/BTP/ChampSim/btb/basic_btb
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb
###

a23dd986_btbDbasic_btb_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb
a23dd986_btbDbasic_btb_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/btb/basic_btb/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb/%.o, $(wildcard /home/neeraj/BTP/ChampSim/btb/basic_btb/*.cc))
$(a23dd986_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/btb/basic_btb
$(a23dd986_btbDbasic_btb_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb/%.o: /home/neeraj/BTP/ChampSim/btb/basic_btb/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/btbDbasic_btb/*.d)

$(a23dd986_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(a23dd986_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(a23dd986_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
$(a23dd986_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(a23dd986_btbDbasic_btb_dirs_0)
module_objs += $(a23dd986_btbDbasic_btb_objs_0)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_btbDbasic_btb_objs_0)
###
# Build ID: a23dd986_branchDbimodal
# Source: /home/neeraj/BTP/ChampSim/branch/bimodal
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal
###

a23dd986_branchDbimodal_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal
a23dd986_branchDbimodal_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/branch/bimodal/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal/%.o, $(wildcard /home/neeraj/BTP/ChampSim/branch/bimodal/*.cc))
$(a23dd986_branchDbimodal_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/branch/bimodal
$(a23dd986_branchDbimodal_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal/%.o: /home/neeraj/BTP/ChampSim/branch/bimodal/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/branchDbimodal/*.d)

$(a23dd986_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(a23dd986_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(a23dd986_branchDbimodal_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
$(a23dd986_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(a23dd986_branchDbimodal_dirs_0)
module_objs += $(a23dd986_branchDbimodal_objs_0)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_branchDbimodal_objs_0)
###
# Build ID: a23dd986_prefetcherDno
# Source: /home/neeraj/BTP/ChampSim/prefetcher/no
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno
###

a23dd986_prefetcherDno_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno
a23dd986_prefetcherDno_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/no/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/no/*.cc))
$(a23dd986_prefetcherDno_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/no
$(a23dd986_prefetcherDno_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno/%.o: /home/neeraj/BTP/ChampSim/prefetcher/no/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno/*.d)

$(a23dd986_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(a23dd986_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(a23dd986_prefetcherDno_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
$(a23dd986_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(a23dd986_prefetcherDno_dirs_0)
module_objs += $(a23dd986_prefetcherDno_objs_0)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_prefetcherDno_objs_0)
###
# Build ID: a23dd986_prefetcherDno_instr
# Source: /home/neeraj/BTP/ChampSim/prefetcher/no_instr
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr
###

a23dd986_prefetcherDno_instr_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr
a23dd986_prefetcherDno_instr_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/no_instr/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/no_instr/*.cc))
$(a23dd986_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/no_instr
$(a23dd986_prefetcherDno_instr_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr/%.o: /home/neeraj/BTP/ChampSim/prefetcher/no_instr/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/prefetcherDno_instr/*.d)

$(a23dd986_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(a23dd986_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(a23dd986_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
$(a23dd986_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(a23dd986_prefetcherDno_instr_dirs_0)
module_objs += $(a23dd986_prefetcherDno_instr_objs_0)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_prefetcherDno_instr_objs_0)
###
# Build ID: a23dd986_replacementDlru
# Source: /home/neeraj/BTP/ChampSim/replacement/lru
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru
###

a23dd986_replacementDlru_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru
a23dd986_replacementDlru_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/replacement/lru/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru/%.o, $(wildcard /home/neeraj/BTP/ChampSim/replacement/lru/*.cc))
$(a23dd986_replacementDlru_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/replacement/lru
$(a23dd986_replacementDlru_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru/%.o: /home/neeraj/BTP/ChampSim/replacement/lru/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/a23dd986/replacementDlru/*.d)

$(a23dd986_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(a23dd986_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(a23dd986_replacementDlru_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/a23dd986/inc
$(a23dd986_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(a23dd986_replacementDlru_dirs_0)
module_objs += $(a23dd986_replacementDlru_objs_0)

/home/neeraj/BTP/ChampSim/bin/champsim: $(a23dd986_replacementDlru_objs_0)

######
# Build ID: 005defd2
# Executable: /home/neeraj/BTP/ChampSim/test/bin/000-test-main
######

###
# Build ID: 005defd2
# Source: /home/neeraj/BTP/ChampSim/test/cpp/src
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
###

005defd2_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
005defd2_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/src/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/src/*.cc))
$(005defd2_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/src
$(005defd2_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/%.o: /home/neeraj/BTP/ChampSim/test/cpp/src/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/*.d)

###
# Build ID: 005defd2
# Source: /home/neeraj/BTP/ChampSim/src
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
###

005defd2_dirs_1 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
005defd2_objs_1 = $(patsubst /home/neeraj/BTP/ChampSim/src/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/%.o, $(wildcard /home/neeraj/BTP/ChampSim/src/*.cc))
$(005defd2_objs_1): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/src
$(005defd2_objs_1): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/%.o: /home/neeraj/BTP/ChampSim/src/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/obj/*.d)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_objs_0) $(005defd2_objs_1) | /home/neeraj/BTP/ChampSim/test/bin
$(005defd2_objs_0) $(005defd2_objs_1): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
build_dirs += $(005defd2_dirs_0) $(005defd2_dirs_1) /home/neeraj/BTP/ChampSim/test/bin
build_objs += $(005defd2_objs_0) $(005defd2_objs_1)
executable_name += /home/neeraj/BTP/ChampSim/test/bin/000-test-main

###
# Build ID: 005defd2_btbDbasic_btb
# Source: /home/neeraj/BTP/ChampSim/btb/basic_btb
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb
###

005defd2_btbDbasic_btb_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb
005defd2_btbDbasic_btb_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/btb/basic_btb/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb/%.o, $(wildcard /home/neeraj/BTP/ChampSim/btb/basic_btb/*.cc))
$(005defd2_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/btb/basic_btb
$(005defd2_btbDbasic_btb_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb/%.o: /home/neeraj/BTP/ChampSim/btb/basic_btb/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/btbDbasic_btb/*.d)

$(005defd2_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(005defd2_btbDbasic_btb_dirs_0)
module_objs += $(005defd2_btbDbasic_btb_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_btbDbasic_btb_objs_0)
###
# Build ID: 005defd2_branchDbimodal
# Source: /home/neeraj/BTP/ChampSim/branch/bimodal
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal
###

005defd2_branchDbimodal_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal
005defd2_branchDbimodal_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/branch/bimodal/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal/%.o, $(wildcard /home/neeraj/BTP/ChampSim/branch/bimodal/*.cc))
$(005defd2_branchDbimodal_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/branch/bimodal
$(005defd2_branchDbimodal_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal/%.o: /home/neeraj/BTP/ChampSim/branch/bimodal/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDbimodal/*.d)

$(005defd2_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_branchDbimodal_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(005defd2_branchDbimodal_dirs_0)
module_objs += $(005defd2_branchDbimodal_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_branchDbimodal_objs_0)
###
# Build ID: 005defd2_branchDgshare
# Source: /home/neeraj/BTP/ChampSim/branch/gshare
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare
###

005defd2_branchDgshare_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare
005defd2_branchDgshare_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/branch/gshare/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare/%.o, $(wildcard /home/neeraj/BTP/ChampSim/branch/gshare/*.cc))
$(005defd2_branchDgshare_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/branch/gshare
$(005defd2_branchDgshare_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare/%.o: /home/neeraj/BTP/ChampSim/branch/gshare/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDgshare/*.d)

$(005defd2_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_branchDgshare_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_branchDgshare_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
module_dirs += $(005defd2_branchDgshare_dirs_0)
module_objs += $(005defd2_branchDgshare_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_branchDgshare_objs_0)
###
# Build ID: 005defd2_branchDhashed_perceptron
# Source: /home/neeraj/BTP/ChampSim/branch/hashed_perceptron
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron
###

005defd2_branchDhashed_perceptron_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron
005defd2_branchDhashed_perceptron_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/branch/hashed_perceptron/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron/%.o, $(wildcard /home/neeraj/BTP/ChampSim/branch/hashed_perceptron/*.cc))
$(005defd2_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/branch/hashed_perceptron
$(005defd2_branchDhashed_perceptron_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron/%.o: /home/neeraj/BTP/ChampSim/branch/hashed_perceptron/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDhashed_perceptron/*.d)

$(005defd2_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_branchDhashed_perceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
module_dirs += $(005defd2_branchDhashed_perceptron_dirs_0)
module_objs += $(005defd2_branchDhashed_perceptron_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_branchDhashed_perceptron_objs_0)
###
# Build ID: 005defd2_branchDperceptron
# Source: /home/neeraj/BTP/ChampSim/branch/perceptron
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron
###

005defd2_branchDperceptron_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron
005defd2_branchDperceptron_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/branch/perceptron/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron/%.o, $(wildcard /home/neeraj/BTP/ChampSim/branch/perceptron/*.cc))
$(005defd2_branchDperceptron_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/branch/perceptron
$(005defd2_branchDperceptron_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron/%.o: /home/neeraj/BTP/ChampSim/branch/perceptron/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/branchDperceptron/*.d)

$(005defd2_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_branchDperceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_branchDperceptron_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
module_dirs += $(005defd2_branchDperceptron_dirs_0)
module_objs += $(005defd2_branchDperceptron_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_branchDperceptron_objs_0)
###
# Build ID: 005defd2_prefetcherDip_stride
# Source: /home/neeraj/BTP/ChampSim/prefetcher/ip_stride
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride
###

005defd2_prefetcherDip_stride_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride
005defd2_prefetcherDip_stride_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/ip_stride/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/ip_stride/*.cc))
$(005defd2_prefetcherDip_stride_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/ip_stride
$(005defd2_prefetcherDip_stride_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride/%.o: /home/neeraj/BTP/ChampSim/prefetcher/ip_stride/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDip_stride/*.d)

$(005defd2_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDip_stride_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDip_stride_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
module_dirs += $(005defd2_prefetcherDip_stride_dirs_0)
module_objs += $(005defd2_prefetcherDip_stride_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDip_stride_objs_0)
###
# Build ID: 005defd2_prefetcherDnext_line
# Source: /home/neeraj/BTP/ChampSim/prefetcher/next_line
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line
###

005defd2_prefetcherDnext_line_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line
005defd2_prefetcherDnext_line_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/next_line/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/next_line/*.cc))
$(005defd2_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/next_line
$(005defd2_prefetcherDnext_line_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line/%.o: /home/neeraj/BTP/ChampSim/prefetcher/next_line/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line/*.d)

$(005defd2_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDnext_line_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
module_dirs += $(005defd2_prefetcherDnext_line_dirs_0)
module_objs += $(005defd2_prefetcherDnext_line_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDnext_line_objs_0)
###
# Build ID: 005defd2_prefetcherDnext_line_instr
# Source: /home/neeraj/BTP/ChampSim/prefetcher/next_line_instr
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr
###

005defd2_prefetcherDnext_line_instr_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr
005defd2_prefetcherDnext_line_instr_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/next_line_instr/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/next_line_instr/*.cc))
$(005defd2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/next_line_instr
$(005defd2_prefetcherDnext_line_instr_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr/%.o: /home/neeraj/BTP/ChampSim/prefetcher/next_line_instr/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDnext_line_instr/*.d)

$(005defd2_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
module_dirs += $(005defd2_prefetcherDnext_line_instr_dirs_0)
module_objs += $(005defd2_prefetcherDnext_line_instr_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDnext_line_instr_objs_0)
###
# Build ID: 005defd2_prefetcherDno
# Source: /home/neeraj/BTP/ChampSim/prefetcher/no
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno
###

005defd2_prefetcherDno_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno
005defd2_prefetcherDno_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/no/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/no/*.cc))
$(005defd2_prefetcherDno_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/no
$(005defd2_prefetcherDno_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno/%.o: /home/neeraj/BTP/ChampSim/prefetcher/no/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno/*.d)

$(005defd2_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDno_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(005defd2_prefetcherDno_dirs_0)
module_objs += $(005defd2_prefetcherDno_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDno_objs_0)
###
# Build ID: 005defd2_prefetcherDno_instr
# Source: /home/neeraj/BTP/ChampSim/prefetcher/no_instr
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr
###

005defd2_prefetcherDno_instr_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr
005defd2_prefetcherDno_instr_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/no_instr/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/no_instr/*.cc))
$(005defd2_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/no_instr
$(005defd2_prefetcherDno_instr_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr/%.o: /home/neeraj/BTP/ChampSim/prefetcher/no_instr/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDno_instr/*.d)

$(005defd2_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(005defd2_prefetcherDno_instr_dirs_0)
module_objs += $(005defd2_prefetcherDno_instr_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDno_instr_objs_0)
###
# Build ID: 005defd2_prefetcherDspp_dev
# Source: /home/neeraj/BTP/ChampSim/prefetcher/spp_dev
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev
###

005defd2_prefetcherDspp_dev_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev
005defd2_prefetcherDspp_dev_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/spp_dev/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/spp_dev/*.cc))
$(005defd2_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/spp_dev
$(005defd2_prefetcherDspp_dev_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev/%.o: /home/neeraj/BTP/ChampSim/prefetcher/spp_dev/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDspp_dev/*.d)

$(005defd2_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDspp_dev_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
module_dirs += $(005defd2_prefetcherDspp_dev_dirs_0)
module_objs += $(005defd2_prefetcherDspp_dev_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDspp_dev_objs_0)
###
# Build ID: 005defd2_prefetcherDva_ampm_lite
# Source: /home/neeraj/BTP/ChampSim/prefetcher/va_ampm_lite
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite
###

005defd2_prefetcherDva_ampm_lite_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite
005defd2_prefetcherDva_ampm_lite_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/prefetcher/va_ampm_lite/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite/%.o, $(wildcard /home/neeraj/BTP/ChampSim/prefetcher/va_ampm_lite/*.cc))
$(005defd2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/prefetcher/va_ampm_lite
$(005defd2_prefetcherDva_ampm_lite_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite/%.o: /home/neeraj/BTP/ChampSim/prefetcher/va_ampm_lite/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/prefetcherDva_ampm_lite/*.d)

$(005defd2_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
module_dirs += $(005defd2_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(005defd2_prefetcherDva_ampm_lite_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_prefetcherDva_ampm_lite_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDprefetcherDaddress_collector
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/address_collector
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector
###

005defd2_testDcppDmodulesDprefetcherDaddress_collector_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector
005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/address_collector/*.cc))
$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/address_collector
$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDaddress_collector/*.d)

$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDaddress_collector.inc
module_dirs += $(005defd2_testDcppDmodulesDprefetcherDaddress_collector_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDprefetcherDaddress_collector_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDprefetcherDmetadata_collector
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_collector
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector
###

005defd2_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector
005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_collector/*.cc))
$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_collector
$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_collector/*.d)

$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_collector.inc
module_dirs += $(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDprefetcherDmetadata_emitter
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter
###

005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter
005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/*.cc))
$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDmetadata_emitter/*.d)

$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_emitter.inc
module_dirs += $(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector
###

005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector
005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/*.cc))
$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDprefetcherDprefetch_hit_collector/*.d)

$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDprefetch_hit_collector.inc
module_dirs += $(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)
###
# Build ID: 005defd2_replacementDdrrip
# Source: /home/neeraj/BTP/ChampSim/replacement/drrip
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip
###

005defd2_replacementDdrrip_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip
005defd2_replacementDdrrip_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/replacement/drrip/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip/%.o, $(wildcard /home/neeraj/BTP/ChampSim/replacement/drrip/*.cc))
$(005defd2_replacementDdrrip_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/replacement/drrip
$(005defd2_replacementDdrrip_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip/%.o: /home/neeraj/BTP/ChampSim/replacement/drrip/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDdrrip/*.d)

$(005defd2_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_replacementDdrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_replacementDdrrip_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
module_dirs += $(005defd2_replacementDdrrip_dirs_0)
module_objs += $(005defd2_replacementDdrrip_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_replacementDdrrip_objs_0)
###
# Build ID: 005defd2_replacementDlru
# Source: /home/neeraj/BTP/ChampSim/replacement/lru
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru
###

005defd2_replacementDlru_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru
005defd2_replacementDlru_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/replacement/lru/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru/%.o, $(wildcard /home/neeraj/BTP/ChampSim/replacement/lru/*.cc))
$(005defd2_replacementDlru_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/replacement/lru
$(005defd2_replacementDlru_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru/%.o: /home/neeraj/BTP/ChampSim/replacement/lru/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDlru/*.d)

$(005defd2_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_replacementDlru_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(005defd2_replacementDlru_dirs_0)
module_objs += $(005defd2_replacementDlru_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_replacementDlru_objs_0)
###
# Build ID: 005defd2_replacementDship
# Source: /home/neeraj/BTP/ChampSim/replacement/ship
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship
###

005defd2_replacementDship_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship
005defd2_replacementDship_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/replacement/ship/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship/%.o, $(wildcard /home/neeraj/BTP/ChampSim/replacement/ship/*.cc))
$(005defd2_replacementDship_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/replacement/ship
$(005defd2_replacementDship_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship/%.o: /home/neeraj/BTP/ChampSim/replacement/ship/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDship/*.d)

$(005defd2_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_replacementDship_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_replacementDship_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
module_dirs += $(005defd2_replacementDship_dirs_0)
module_objs += $(005defd2_replacementDship_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_replacementDship_objs_0)
###
# Build ID: 005defd2_replacementDsrrip
# Source: /home/neeraj/BTP/ChampSim/replacement/srrip
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip
###

005defd2_replacementDsrrip_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip
005defd2_replacementDsrrip_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/replacement/srrip/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip/%.o, $(wildcard /home/neeraj/BTP/ChampSim/replacement/srrip/*.cc))
$(005defd2_replacementDsrrip_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/replacement/srrip
$(005defd2_replacementDsrrip_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip/%.o: /home/neeraj/BTP/ChampSim/replacement/srrip/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/replacementDsrrip/*.d)

$(005defd2_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_replacementDsrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_replacementDsrrip_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
module_dirs += $(005defd2_replacementDsrrip_dirs_0)
module_objs += $(005defd2_replacementDsrrip_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_replacementDsrrip_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDreplacementDlru_collect
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/lru_collect
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect
###

005defd2_testDcppDmodulesDreplacementDlru_collect_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect
005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/lru_collect/*.cc))
$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/lru_collect
$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDlru_collect/*.d)

$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDlru_collect.inc
module_dirs += $(005defd2_testDcppDmodulesDreplacementDlru_collect_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDreplacementDlru_collect_objs_0)
###
# Build ID: 005defd2_testDcppDmodulesDreplacementDmock_replacement
# Source: /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/mock_replacement
# Destination: /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement
###

005defd2_testDcppDmodulesDreplacementDmock_replacement_dirs_0 = /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement
005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0 = $(patsubst /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc, /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement/%.o, $(wildcard /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/mock_replacement/*.cc))
$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/mock_replacement
$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement/%.o: /home/neeraj/BTP/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc | /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement
-include $(wildcard /home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/testDcppDmodulesDreplacementDmock_replacement/*.d)

$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): CXXFLAGS += -Wno-unused-parameter
$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/home/neeraj/BTP/ChampSim/.csconfig/test/005defd2/inc
$(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDmock_replacement.inc
module_dirs += $(005defd2_testDcppDmodulesDreplacementDmock_replacement_dirs_0)
module_objs += $(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0)

/home/neeraj/BTP/ChampSim/test/bin/000-test-main: $(005defd2_testDcppDmodulesDreplacementDmock_replacement_objs_0)
